### ISSUE TITLE
Is it `description` or `summary` in page information ?

### ISSUE THREAD

**Issue by AmirAref** [st1020/kita#10]
There are two definition as page's `description` or page's `summary`.  
Somewhere in the templates, the `summary` has been used, such as here in [templates/partials/head.html](https://github.com/st1020/kita/blob/3d4a16867677efe688d7e0cc4ee32f06198f0a40/templates/partials/head.html#L18).
And another place in [templates/partials/page_list.html](https://github.com/st1020/kita/blob/3d4a16867677efe688d7e0cc4ee32f06198f0a40/templates/partials/head.html#L18) both of them has been handled.
And in the [sample contents](https://github.com/st1020/kita/blob/3d4a16867677efe688d7e0cc4ee32f06198f0a40/content/markdown-syntax.md?plain=1#L4), the `description` has been used.

So I think it's better to use one exact definition to avoid this duality (or we should handle both of them everywhere).

**Comment by st1020** [comment]
Yes, you are right, the page's `description` and page's `summary` is different. And the description `<meta>` tag should use `description ` instead of `summary`.

I fixed it in https://github.com/st1020/kita/commit/2c1452673dae803d85b5c12ce4d888cc5a996ea6.
