### ISSUE TITLE
Site disclaimer

### ISSUE THREAD

**Issue by lopes** [st1020/kita#12]
It's not an issue but a feature request. It would be great to have a way to insert a general purpose and optional disclaimer (in the footer, for example).

Personally, I wanted to use it to display privacy information (no cookies) and show a "not AI" message or badge. It could be kind of a text box allowing HTML content.

What do you think?

Congrats for the amazing theme!

**Comment by st1020** [comment]
Thanks for your advice.
You can create a template file at `templates/partials/page_info.html` to customize page footer. I think this should be customizable enough.
