### ISSUE TITLE
Error: Failed to serve the site | Failed to parse "/var/blog/templates/kita/content/shortcodes/index.md"

### ISSUE THREAD

**Issue by preis98** [st1020/kita#21]
I followed your instructions but either you forgot a step or there is an error in the theme

Error: Error parsing templates from the /templates directory
Error: Reason:
* Failed to parse "/var/blog/templates/kita/content/shortcodes/index.md"
  --> 31:1
   |
31 | {%/* mermaid() */%}
   | ^---
   |
   = unexpected tag; expected end of input, a macro definition tag (`{% macro my_macro() %}`, or some content

# The URL the site will be built for
base_url = "https://example.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
theme = "kita"

Specs: 
Debian 12 Bookworm
4 Cores
8GB RAM

Command:
cd /var/
mkdir blog
zola init blog

git clone https://github.com/st1020/kita.git themes/kita
zola serve --interface 0.0.0.0 --port 80 --base-url /

**Comment by st1020** [comment]
This is not a problem with the theme, but a problem with your configuration. You should not set `theme = "kita"` in `[extra]` section, set it in root section instead.

Please refer: https://www.getzola.org/documentation/getting-started/configuration/

**Comment by preis98** [comment]
That is Not the Solution. The error persists

**Comment by st1020** [comment]
You can try to see if the following command is executed successfully:

```sh
git clone --recurse-submodules https://github.com/st1020/blog.git
cd blog
zola build
```
