### ISSUE TITLE
make showing page reading time optional

### ISSUE THREAD

**Issue by craftyguy** [st1020/kita#3]
IMHO `page.reading_time` is kind of silly, since not everyone reads at the same speed. Would you consider making this optional?

**Comment by st1020** [comment]
The `reading_time` of Zola is based on [Medium read time](https://help.medium.com/hc/en-us/articles/214991667-Read-time), which reflected the average human reading speed.

Actually, you can create a template file at `templates/partials/page_info.html` to customize your own page information.

Like replce `reading_time` to `word_count`:

```html
<div class="text-sm antialiased opacity-60">
  {% if page.date %}
  <time>{{ page.date | date }}</time>
  <span class="mx-1">&middot;</span>
  <span>{{ page.word_count }} words</span>
  {% endif %}<!---->
  {% set single_author = page.extra.author | default(value=config.author) %}
  <!---->
  {% if single_author %}
  <span class="mx-1">&middot;</span>
  <span>{{ single_author }}</span>
  {% endif %}
</div>
```
