### ISSUE TITLE
Mermaid charts don't follow dark mode

### ISSUE THREAD

**Issue by lopes** [st1020/kita#8]
Not exactly an issue, but a Feature Request. Mermaid provides some alternative themes as shown [here](https://mermaid.js.org/config/theming.html).

Kita could change the theme according to the user preference (`light`/`dark`) or the admin could set the theme in the post's header or in `config.toml`.

Something like:

```yaml
mermaid = true
mermaid_theme = forest
```

PS: Congrats for this amazing theme. :)

**Comment by st1020** [comment]
Thanks for your advice. I added the feature of re-rendering mermaid when theme changed in https://github.com/st1020/kita/commit/be0ec891a0a26f45711826028f75cb0ff833c2a4, I hope this solves your problem.

In addition, you can create `templates/partials/mermaid.html` file and write the following content to use a custom mermaid theme globally:

```html
<script type="module">
import mermaid from "https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs";

mermaid.initialize({ theme: "dark", startOnLoad: true });
mermaid.run();
</script>
```

Or you can use use the `init` directive to customize the theme of an individual diagram, see [Mermaid Document](https://mermaid.js.org/config/theming.html#diagram-specific-themes) for more detail.

If you have any other advice, please feel free to ask.

**Comment by lopes** [comment]
It worked beautifully, thanks! 👏 👏 👊
